language: python
python: ["3.6"]
cache:
    pip: true
    directories:
        - $HOME/.cache/pre-commit

addons:
  apt:
    update: true
    packages:
      - libcurl4-openssl-dev

install:
    - pip3 install -r .travis/requirements.txt

script: .travis/run-pre-commit
