language: python
cache:
    pip: true
    directories:
        - $HOME/.cache/pre-commit

addons:
  apt:
    update: true
    packages: libcurl4-openssl-dev

install:
    - pip install -r .travis/requirements.txt

script: .travis/run-pre-commit
